services:

  # Cloudflare Tunnel Service
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    hostname: cloudflare-tunnel
    restart: unless-stopped
    network_mode: "host"
    command: tunnel run
    environment:
      - "TUNNEL_TOKEN=${TOKEN}"
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
  # Podsync Vodcast Service
  podsync:
    container_name: podsync
    image: ghcr.io/mxpv/podsync:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./data:/app/data/
      - ./podsync-config.toml:/app/config.toml
